//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Label {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Label", typeof(Label).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره چرم مشهد.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تهران، خیابان ولیعصر، خیابان شهید عاطفی.
        /// </summary>
        public static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پلاک 100 طبقه پنجم.
        /// </summary>
        public static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشهد - میدان جانباز - ساختمان پاژ.
        /// </summary>
        public static string Address3 {
            get {
                return ResourceManager.GetString("Address3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساختمان اداری شماره 2 - طبقه 9 - واحد 911.
        /// </summary>
        public static string Address4 {
            get {
                return ResourceManager.GetString("Address4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس و نقشه.
        /// </summary>
        public static string AddressMap {
            get {
                return ResourceManager.GetString("AddressMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن به سبد خرید.
        /// </summary>
        public static string addtobasket {
            get {
                return ResourceManager.GetString("addtobasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقالات.
        /// </summary>
        public static string article {
            get {
                return ResourceManager.GetString("article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرفروش ترین محصولات.
        /// </summary>
        public static string BestsellingProducts {
            get {
                return ResourceManager.GetString("BestsellingProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وبلاگ.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعب.
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تماس شعب چرم مشهد.
        /// </summary>
        public static string BranchInfo {
            get {
                return ResourceManager.GetString("BranchInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شعبه.
        /// </summary>
        public static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راهنمای خرید.
        /// </summary>
        public static string BuyGuid {
            get {
                return ResourceManager.GetString("BuyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همکاران ما در اسراع وقت با شما تماس می گیرند..
        /// </summary>
        public static string CallYou {
            get {
                return ResourceManager.GetString("CallYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل.
        /// </summary>
        public static string CellNumber {
            get {
                return ResourceManager.GetString("CellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب رنگ.
        /// </summary>
        public static string ChooseColor {
            get {
                return ResourceManager.GetString("ChooseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب سایز.
        /// </summary>
        public static string ChooseSize {
            get {
                return ResourceManager.GetString("ChooseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یادداشت.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوالات متداول.
        /// </summary>
        public static string ComonQuestions {
            get {
                return ResourceManager.GetString("ComonQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تماس.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همکاری با چرم مشهد.
        /// </summary>
        public static string Cooperation {
            get {
                return ResourceManager.GetString("Cooperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همکاری با چرم مشهد از طریق لینک زیر.
        /// </summary>
        public static string CooperationMainText {
            get {
                return ResourceManager.GetString("CooperationMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باشگاه مشتریان.
        /// </summary>
        public static string CustomerClub {
            get {
                return ResourceManager.GetString("CustomerClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوانین باشگاه مشتریان.
        /// </summary>
        public static string CustomerClubPrivacy {
            get {
                return ResourceManager.GetString("CustomerClubPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده پروفایل.
        /// </summary>
        public static string CustomerClubProfile {
            get {
                return ResourceManager.GetString("CustomerClubProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مشتری.
        /// </summary>
        public static string CustomerInfo {
            get {
                return ResourceManager.GetString("CustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات مشتریان.
        /// </summary>
        public static string CustomerService {
            get {
                return ResourceManager.GetString("CustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخگوی تمامی پرسش های شما.
        /// </summary>
        public static string CustomerServiceDesc {
            get {
                return ResourceManager.GetString("CustomerServiceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفیف.
        /// </summary>
        public static string discountPrice {
            get {
                return ResourceManager.GetString("discountPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبد خرید شما خالی می باشد.
        /// </summary>
        public static string EmptyBasket {
            get {
                return ResourceManager.GetString("EmptyBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا آدرس ایمیل خود را وارد کنید.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تلفن همراه خود را وارد کنید.
        /// </summary>
        public static string EnterMobile {
            get {
                return ResourceManager.GetString("EnterMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یورو.
        /// </summary>
        public static string Euro {
            get {
                return ResourceManager.GetString("Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صادرات.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس کارخانه.
        /// </summary>
        public static string FactoryAddress {
            get {
                return ResourceManager.GetString("FactoryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نهایی کردن خرید آنلاین.
        /// </summary>
        public static string Finlize {
            get {
                return ResourceManager.GetString("Finlize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال رایگان به سراسر ایران.
        /// </summary>
        public static string FreeShipping {
            get {
                return ResourceManager.GetString("FreeShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای سفارشات بالای 300 هزار تومان.
        /// </summary>
        public static string FreeShippingDesc {
            get {
                return ResourceManager.GetString("FreeShippingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گالری.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گوگل مپ.
        /// </summary>
        public static string GoogleMap {
            get {
                return ResourceManager.GetString("GoogleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست سفارشات.
        /// </summary>
        public static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه اصلی.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از جمله افتخارات چرم مشهد.
        /// </summary>
        public static string Honors {
            get {
                return ResourceManager.GetString("Honors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل یا تلفن خود را وارد کنید.
        /// </summary>
        public static string InsertNewsletter {
            get {
                return ResourceManager.GetString("InsertNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاع از آخرین محصولات و رویداد ها.
        /// </summary>
        public static string LatestProductsandEvents {
            get {
                return ResourceManager.GetString("LatestProductsandEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چرم مشهد.
        /// </summary>
        public static string MashadLeather {
            get {
                return ResourceManager.GetString("MashadLeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعب چرم مشهد.
        /// </summary>
        public static string MashadLeatherBranches {
            get {
                return ResourceManager.GetString("MashadLeatherBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گالری چرم مشهد.
        /// </summary>
        public static string MashadLeatherGallery {
            get {
                return ResourceManager.GetString("MashadLeatherGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشگاه اینترنتی چرم مشهد.
        /// </summary>
        public static string MashadLeatherStore {
            get {
                return ResourceManager.GetString("MashadLeatherStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس دفتر مشهد.
        /// </summary>
        public static string MashadOfficeAddress {
            get {
                return ResourceManager.GetString("MashadOfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن همراه.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخبار.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با عضویت در خبر نامه ما از آخرین آفر های فصلی زود تر از بقیه با خبر شوید.
        /// </summary>
        public static string newsletterJoin {
            get {
                return ResourceManager.GetString("newsletterJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن فروشگاه اینترنتی.
        /// </summary>
        public static string OnlineStorePhone {
            get {
                return ResourceManager.GetString("OnlineStorePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمع فاکتور.
        /// </summary>
        public static string OrderSum {
            get {
                return ResourceManager.GetString("OrderSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیگیری سفارش.
        /// </summary>
        public static string OrderTracking {
            get {
                return ResourceManager.GetString("OrderTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروش سازمانی.
        /// </summary>
        public static string OrganizationalSales {
            get {
                return ResourceManager.GetString("OrganizationalSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر مطالب وبلاگ.
        /// </summary>
        public static string OtherBlogContent {
            get {
                return ResourceManager.GetString("OtherBlogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیگر اعضای گروه صنعتی مشهد.
        /// </summary>
        public static string OtherMembers {
            get {
                return ResourceManager.GetString("OtherMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن ثابت.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوانین و مقررات.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایت را مطالعه کرده ام و قبول دارم..
        /// </summary>
        public static string PolicyRead {
            get {
                return ResourceManager.GetString("PolicyRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت واحد.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات محصولات.
        /// </summary>
        public static string ProductInformation {
            get {
                return ResourceManager.GetString("ProductInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت کالا.
        /// </summary>
        public static string ProductReturn {
            get {
                return ResourceManager.GetString("ProductReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت حفظ سلامتی مشتریان عزیز در این ایام تعویض و مرجوع کردن کالا امکان پذیر نمیباشد.
        /// </summary>
        public static string ProductReturnDesc {
            get {
                return ResourceManager.GetString("ProductReturnDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشگاه اینترنتی.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی سریع.
        /// </summary>
        public static string QuickAccess {
            get {
                return ResourceManager.GetString("QuickAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده سریع.
        /// </summary>
        public static string QuickView {
            get {
                return ResourceManager.GetString("QuickView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادامه مطلب.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدیدترین محصولات.
        /// </summary>
        public static string RecentProducts {
            get {
                return ResourceManager.GetString("RecentProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخ.
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت به فروشگاه.
        /// </summary>
        public static string ReturnToStore {
            get {
                return ResourceManager.GetString("ReturnToStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریال.
        /// </summary>
        public static string Rial {
            get {
                return ResourceManager.GetString("Rial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیریابی.
        /// </summary>
        public static string Routing {
            get {
                return ResourceManager.GetString("Routing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ دوم.
        /// </summary>
        public static string SecondColor {
            get {
                return ResourceManager.GetString("SecondColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب رنگ.
        /// </summary>
        public static string SelectColor {
            get {
                return ResourceManager.GetString("SelectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به اشتراک گذاری محصول.
        /// </summary>
        public static string ShareProduct {
            get {
                return ResourceManager.GetString("ShareProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه ارسال.
        /// </summary>
        public static string SheepmentPrice {
            get {
                return ResourceManager.GetString("SheepmentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشگاه ها.
        /// </summary>
        public static string Stores {
            get {
                return ResourceManager.GetString("Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایندگی های ما را بر روی نقشه بیابید.
        /// </summary>
        public static string StoresDesc {
            get {
                return ResourceManager.GetString("StoresDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع/نام.
        /// </summary>
        public static string Subject_Name {
            get {
                return ResourceManager.GetString("Subject_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این کالا با موفقیت به سبد خرید افزوده شد. جهت مشاهده سبد خرید و نهایی سازی خرید اینجا را کلیک کنید..
        /// </summary>
        public static string Success_AddToBasket {
            get {
                return ResourceManager.GetString("Success_AddToBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام شما با موفقیت ارسال شد..
        /// </summary>
        public static string Success_Message {
            get {
                return ResourceManager.GetString("Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفتر تهران.
        /// </summary>
        public static string TehranOffice {
            get {
                return ResourceManager.GetString("TehranOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با تشکر.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع هزینه ها.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع قابل پرداخت.
        /// </summary>
        public static string TotalPayment {
            get {
                return ResourceManager.GetString("TotalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروزرسانی سبد خرید.
        /// </summary>
        public static string UpdateBasket {
            get {
                return ResourceManager.GetString("UpdateBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شنبه تا پنجشنبه:.
        /// </summary>
        public static string WorkTime {
            get {
                return ResourceManager.GetString("WorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما.
        /// </summary>
        public static string you {
            get {
                return ResourceManager.GetString("you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبد خرید شما.
        /// </summary>
        public static string yourBasket {
            get {
                return ResourceManager.GetString("yourBasket", resourceCulture);
            }
        }
    }
}
