//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج با موفقیت انجام شد.
        /// </summary>
        public static string Account_Logout_Success {
            get {
                return ResourceManager.GetString("Account_Logout_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل وارد شده صحیح نمی باشد.
        /// </summary>
        public static string EmailExpersionValidation {
            get {
                return ResourceManager.GetString("EmailExpersionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در پردازش اطلاعات.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل وارد شده معتبر نمی باشد.
        /// </summary>
        public static string InvalidCellNumber {
            get {
                return ResourceManager.GetString("InvalidCellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده صحیح نمی باشد.
        /// </summary>
        public static string InvalidChangeCode {
            get {
                return ResourceManager.GetString("InvalidChangeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاسفانه در حال حاضر سایز و رنگ انتخابی شما موجود نمی باشد. لطفا سایز یا رنگ را تغییر دهید.
        /// </summary>
        public static string InvalidColorAndSize {
            get {
                return ResourceManager.GetString("InvalidColorAndSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر معتبر نمی باشد.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا کلمه عبور صحیح نمی باشد.
        /// </summary>
        public static string Login_BadRequest {
            get {
                return ResourceManager.GetString("Login_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود با موفقیت انجام شد.
        /// </summary>
        public static string Login_SuccessLogin {
            get {
                return ResourceManager.GetString("Login_SuccessLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل وارد شده صحیح نمی باشد.
        /// </summary>
        public static string MobilExpersionValidation {
            get {
                return ResourceManager.GetString("MobilExpersionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن را وارد نمایید.
        /// </summary>
        public static string NullToken {
            get {
                return ResourceManager.GetString("NullToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیغام شما با موفقیت ثبت گردید، پس از تایید مدیر سایت نمایش داده خواهد شد.
        /// </summary>
        public static string SuccessComment {
            get {
                return ResourceManager.GetString("SuccessComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت نمایش داده شد.
        /// </summary>
        public static string SuccessGet {
            get {
                return ResourceManager.GetString("SuccessGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت با موفقیت انجام شد.
        /// </summary>
        public static string SuccessPost {
            get {
                return ResourceManager.GetString("SuccessPost", resourceCulture);
            }
        }
    }
}
